### ISSUE TITLE
ReferenceError: statusCode is not defined

### ISSUE THREAD

**Issue by sunil911** [samholmes/node-open-graph#12]
home/sunil/project/maiden_tales/node_modules/open-graph/index.js:47
				cb(new Error("Request failed with HTTP status code: "+statusCode));
i'm getting error in above line when i give wrong url and the error is : statusCode is not defined.
i think there should be res.statusCode

**Comment by samholmes** [comment]
Fixed: https://github.com/samholmes/node-open-graph/commit/432f869427cec718b41e34b0a519da4226d83421
