### ISSUE TITLE
"Maximum call stack size exceeded" for urls with large HTML source or non HTML source

### ISSUE THREAD

**Issue by semy** [samholmes/node-open-graph#19]
Hi,

thank you for this nice plugin.

It works very well, but sometimes I get an error "Maximum call stack size exceeded" and my complete software crashes. That's a known problem of "cheerio".

Test your plugin e.g. with this url:
https://courses.csail.mit.edu/6.042/spring17/mcs.pdf

You could fix this problem with try...catch, e.g.:
```
exports = module.exports = function(url, cb, options){
  exports.getHTML(url, function(err, html){
    if (err) return cb(err);

    try {
      var parsedMeta = exports.parse(html, options);
    } catch (parseErr) {
      return cb(parseErr);
    }

    cb(null, parsedMeta);
  })
}
```

Thank you for fixing this bug! Greets

**Comment by samholmes** [comment]
Just patched this issue. I will update version number and publish it to npm now.

**Comment by semy** [comment]
Thanks ;)
