### ISSUE TITLE
Arrays created when duplicate og properties

### ISSUE THREAD

**Issue by ryanjyost** [samholmes/node-open-graph#22]
If there are two `og:title` properties in the source html, for example, then the `title` property in the final `meta` object has an array of every `og:title` found in the source html.

Is this behavior desired, or should it limit to one title, description, etc. if there are duplicates? I guess the user can always just grab the first item in the resulting array when processing the meta object.

p.s. this have been invaluable for my project, many thanks

**Comment by samholmes** [comment]
The default behavior right now is to turn multiple open graph properties of the same name into an array value. This way [Arrays](http://ogp.me/#array) can be supported from the Open Graph protocol.
