### ISSUE TITLE
cors error

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [samholmes/node-open-graph#23]
XMLHttpRequest cannot load http://www.naver.com/. Redirect from 'http://www.naver.com/' to 'https://www.naver.com/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.lululala.co.kr:8000' is therefore not allowed access.

how can i do?

**Comment by samholmes** [comment]
Can you show me you're code?

**Comment by herrmannplatz** [comment]
I guess you habe used it in the browser?

**Comment by samholmes** [comment]
This module doesn’t work within the browser because of the same-origin policy. I’m closing this issue as the only way to fix this problem is to not use open-graph in the browser.
