### ISSUE TITLE
Sam - is this still being maintained? Do you need help?

### ISSUE THREAD

**Issue by geoidesic** [samholmes/node-open-graph#34]

**Comment by samholmes** [comment]
I could use the help.

**Comment by geoidesic** [comment]
Please let me know how I can help :)
Can you add some permissions for me or how does it work? Both on git and npm. Please advise.
There are several out of date dependencies and PR's that need merging. I am actively using this library so I would like to get it up to date.

I could fork this repo and then host my own private npm repository to make it work but I think it's better if this is kept in the public domain.

**Comment by samholmes** [comment]
Sounds great! Best way is to fork the repo on GitHub and submit PRs upstream. This will give me a chance to review your work/changes.

**Comment by geoidesic** [comment]
Ok. I can do that but I'll also point out that there are PR's more than a year old still open. Doesn't inspire much faith!

**Comment by samholmes** [comment]
https://github.com/samholmes/node-open-graph/pull/31 is the only outstanding PR and the feedback was never addressed.
